import './style.css'

import './js/image-follow-cursor.js'
import './js/menu.js'
import './js/link-hover.js'
import './js/lenis.js'
import './js/magazine.js'
import './js/post.js'
import './js/hero.js'
import './js/draggable.js'
import './js/pin-title.js'
import './js/clip-path.js'
import './js/footer.js'